/**
 * Vercel Serverless Function Proxy for Gemini API
 * Secures the API Key server-side under GEMINI_API_KEY environment variable.
 */
module.exports = async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { prompt } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'Gemini API key is not configured on the Vercel server. Please add GEMINI_API_KEY in Vercel project environment variables.' });
  }

  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
    const apiResponse = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt
              }
            ]
          }
        ],
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_NONE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_NONE"
          },
          {
            category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            threshold: "BLOCK_NONE"
          },
          {
            category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            threshold: "BLOCK_NONE"
          }
        ]
      })
    });

    if (!apiResponse.ok) {
      const errorText = await apiResponse.text();
      return res.status(apiResponse.status).json({ error: `Gemini API error: ${errorText}` });
    }

    const data = await apiResponse.json();
    
    // Check if the prompt was blocked by safety filters
    if (data.promptFeedback?.blockReason) {
      return res.status(400).json({ error: `Prompt blocked by safety filter: ${data.promptFeedback.blockReason}` });
    }

    // Check if response generation was stopped due to safety or other reasons
    const candidate = data.candidates?.[0];
    if (candidate && candidate.finishReason && candidate.finishReason !== "STOP" && candidate.finishReason !== "MAX_TOKENS") {
      return res.status(400).json({ error: `Response generation stopped: ${candidate.finishReason}` });
    }

    const resultText = candidate?.content?.parts?.[0]?.text || "No response text generated by AI model";
    return res.status(200).json({ result: resultText });
  } catch (error) {
    return res.status(500).json({ error: `Server error: ${error.message}` });
  }
};
